name: Issue output
on: [issues, workflow_dispatch]
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Issue info
        run: echo "${{ github.event.issue.title }}" "${{ github.event.issue.body }}"