name: Pull request workflow
on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - dev-* # dev-some dev-something-else
      - feat/** # feat/text feat/many/text
  workflow_dispatch:
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Issue info
        run: echo "${{ toJSON(github.event) }}" "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Build project
        run: npm run build
      - name: Deploy to server
        run: echo "Deploy to server"